# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpatialseshPlugin
                                 A QGIS plugin
 SpatialseshPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        copyright            : (C) 2026 by Teodora Koleva
        email                : koleva.n.teodora@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Teodora Koleva'
__date__ = '2026-07-08'
__copyright__ = '(C) 2026 by Teodora Koleva'



def classFactory(iface):
    from .SpatialseshPlugin import SpatialseshPlugin
    return SpatialseshPlugin(iface)
