# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SpatialseshPlugin
                                 A QGIS plugin
 SpatialseshPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        copyright            : (C) 2026 by Teodora Koleva
        email                : koleva.n.teodora@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Teodora Koleva"
__date__ = "2026-07-08"
__copyright__ = "(C) 2026 by Teodora Koleva"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import os

from qgis.core import QgsProcessingProvider
from qgis.PyQt.QtGui import QIcon
from .algorithms.DesignatedSite_DistanceAndBearing import (
    DesignatedSite_DistanceAndBearingAlgorithm,
)
from .algorithms.BNG_fix_layer import BNG_FixLayerAlgorithm
from .algorithms.DistanceAndBearing import DistanceAndBearingAlgorithm
from .algorithms.Fix_layer_general import Fix_layer_general
from .algorithms.Union_BNG import Union_BNGAlgorithm


class SpatialseshPluginProvider(QgsProcessingProvider):
    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        pass

    def loadAlgorithms(self):
        algorithms = [
            DistanceAndBearingAlgorithm(),
            DesignatedSite_DistanceAndBearingAlgorithm(),
            Fix_layer_general(),
            BNG_FixLayerAlgorithm(),
            Union_BNGAlgorithm(),
        ]

        for algorithm in algorithms:
            self.addAlgorithm(algorithm)
        # add additional algorithms here
        # self.addAlgorithm(MyOtherAlgorithm())

    def id(self):
        return "Spatialsesh"

    def name(self):
        return self.tr("Spatialsesh")

    def icon(self) -> QIcon:
        return QIcon(
            os.path.join(
                os.path.dirname(__file__),
                "icons",
                "favicon.png",
            )
        )

    def longName(self):
        return self.name()
