# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SpatialseshPlugin
                                 A QGIS plugin
 SpatialseshPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        copyright            : (C) 2026 by Teodora Koleva
        email                : koleva.n.teodora@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Teodora Koleva"
__date__ = "2026-07-08"
__copyright__ = "(C) 2026 by Teodora Koleva"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import os

from qgis.core import QgsApplication
from .SpatialseshPlugin_provider import SpatialseshPluginProvider
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from qgis import processing


class SpatialseshPlugin(object):
    def __init__(self, iface):
        self.iface = iface
        self.provider = None
        self.actions = []
        self.toolbar = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SpatialseshPluginProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=False,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        self.initProcessing()

        self.toolbar = self.iface.addToolBar("SpatialSesh")
        self.toolbar.setObjectName("SpatialSeshToolbar")

        # Distance analysis button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "icon2.png"),
            "Distance Analysis",
            self.run_distance_analysis,
            parent=self.iface.mainWindow(),
        )
        # DesignationsDatabase analysis button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "icon.png"),
            "Designations",
            self.run_designations,
            parent=self.iface.mainWindow(),
        )

        # Fix layer general button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "icon3.png"),
            "Fix layer general",
            self.run_fix_layer_general,
            parent=self.iface.mainWindow(),
        )

        # BNG fix layer button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "favicon.png"),
            "BNG fix layer",
            self.run_BNG_fix,
            parent=self.iface.mainWindow(),
        )

    def run_designations(self):
        processing.execAlgorithmDialog("Spatialsesh:NearestNeighbourDD")

    def run_BNG_fix(self):
        processing.execAlgorithmDialog("Spatialsesh:BNG_FixLayer")

    def run_distance_analysis(self):
        processing.execAlgorithmDialog("Spatialsesh:DistanceAnalysis")

    def run_fix_layer_general(self):
        processing.execAlgorithmDialog("Spatialsesh:FixLayer_general")

    def unload(self):
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None

        if self.toolbar:
            for action in self.actions:
                self.toolbar.removeAction(action)

            self.iface.mainWindow().removeToolBar(self.toolbar)

            self.toolbar = None
