# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SpatialseshPlugin
                                 A QGIS plugin
 SpatialseshPlugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-08
        copyright            : (C) 2026 by Teodora Koleva
        email                : koleva.n.teodora@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = "Teodora Koleva"
__date__ = "2026-07-08"
__copyright__ = "(C) 2026 by Teodora Koleva"

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = "$Format:%H$"

import os

from datetime import datetime, timedelta, timezone
from qgis.core import QgsApplication
from qgis.core import QgsSettings
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from qgis import processing

from qgis.gui import QgsOptionsWidgetFactory

from .SpatialseshPlugin_provider import SpatialseshPluginProvider
from SpatialseshPlugin.gui.license_options import LicenseOptionsWidget

from .licenseseat_api import API_KEY, API_SLUG, LicenseSeatApi


class LicenseOptionsFactory(QgsOptionsWidgetFactory):
    def __init__(self):
        super(QgsOptionsWidgetFactory, self).__init__()

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(__file__), "favicon.png"))

    def createWidget(self, parent):
        return LicenseOptionsWidget(parent)


class SpatialseshPlugin(object):
    def __init__(self, iface):
        self.iface = iface
        self.provider = None
        self.actions = []
        self.toolbar = None

        self.license_api = LicenseSeatApi(
            API_SLUG,
            API_KEY,
        )

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = SpatialseshPluginProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=False,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    # def on_license_check_success(
    #     self,
    #     payload: dict[str, Any],
    # ) -> None:
    #     checked_at = datetime.now(timezone.utc)

    #     QgsSettings().setValue(
    #         "maplango/license_valid",
    #         True,
    #     )

    #     QgsSettings().setValue(
    #         "maplango/licenseLastCheckedAt",
    #         checked_at.isoformat(),
    #     )

    # def on_license_check_error(
    #     self,
    #     error: str,
    # ) -> None:
    #     QgsSettings().setValue(
    #         "maplango/license_valid",
    #         False,
    #     )

    #     print(f"License validation failed: {error}")

    def validate_saved_license(self) -> None:
        settings = QgsSettings()

        license_key = settings.value(
            "maplango/license_key",
            "",
            type=str,
        ).strip()

        if not license_key:
            return

        license_valid = settings.value(
            "maplango/license_valid",
            False,
            type=bool,
        )

        last_checked = settings.value(
            "maplango/licenseLastCheckedAt",
            "",
            type=str,
        )

        is_valid = False

        if license_valid and last_checked:
            try:
                checked_at = datetime.fromisoformat(last_checked)
                valid_until = checked_at + timedelta(days=7)

                if datetime.now(timezone.utc) < valid_until:
                    is_valid = True

            except ValueError:
                pass

        if not is_valid:
            self.iface.messageBar().pushWarning(
                "SpatialSesh",
                "Your SpatialSesh license is not active. "
                "Please validate your license in Settings → Options → SpatialSesh.",
            )

    def initGui(self):
        self.validate_saved_license()
        self.license_options_factory = LicenseOptionsFactory()
        self.license_options_factory.setTitle("SpatialSesh")
        self.iface.registerOptionsWidgetFactory(self.license_options_factory)

        self.initProcessing()

        self.toolbar = self.iface.addToolBar("SpatialSesh")
        self.toolbar.setObjectName("SpatialSeshToolbar")

        # Distance analysis button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "Distance_bearing.svg"),
            "Distance and bearing",
            self.run_distance_analysis,
            parent=self.iface.mainWindow(),
        )
        # DesignationsDatabase analysis button
        self.add_action(
            os.path.join(
                os.path.dirname(__file__), "icons", "Distance_bearing_designated.svg"
            ),
            "Designation site distance and bearing",
            self.run_designations,
            parent=self.iface.mainWindow(),
        )

        # Fix layer general button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "Fix_layer_general.svg"),
            "Fix layer general",
            self.run_fix_layer_general,
            parent=self.iface.mainWindow(),
        )

        # BNG fix layer button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "Fix_layer_BNG.svg"),
            "Fix layer BNG",
            self.run_BNG_fix,
            parent=self.iface.mainWindow(),
        )

        # Union BNG button
        self.add_action(
            os.path.join(os.path.dirname(__file__), "icons", "Union_BNG.png"),
            "Union BNG",
            self.run_union_BNG,
            parent=self.iface.mainWindow(),
        )

    def run_distance_analysis(self):
        processing.execAlgorithmDialog("Spatialsesh:DistanceAndBearing")

    def run_designations(self):
        processing.execAlgorithmDialog("Spatialsesh:DesignatedSiteDistanceAndBearing")

    def run_fix_layer_general(self):
        processing.execAlgorithmDialog("Spatialsesh:FixLayer_general")

    def run_BNG_fix(self):
        processing.execAlgorithmDialog("Spatialsesh:FixLayer_BNG")

    def run_union_BNG(self):
        processing.execAlgorithmDialog("Spatialsesh:Union_BNG")

    def unload(self):
        if self.provider:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None

        if self.toolbar:
            for action in self.actions:
                self.toolbar.removeAction(action)

            self.iface.mainWindow().removeToolBar(self.toolbar)

            self.toolbar = None

        self.iface.unregisterOptionsWidgetFactory(self.license_options_factory)
